"""fleet domain tables

Revision ID: 40b5ec956b93
Revises: dc41d0b4983b
Create Date: 2026-07-16 11:51:02.644908+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "40b5ec956b93"
down_revision: str | None = "dc41d0b4983b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drivers",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("license_number_enc", sa.String(length=400), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active','inactive')", name=op.f("ck_drivers_status_valid")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_drivers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_drivers_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drivers")),
        sa.UniqueConstraint("organization_id", "external_id", name="uq_drivers_org_external"),
    )
    op.create_index("ix_drivers_organization_id", "drivers", ["organization_id"], unique=False)
    op.create_table(
        "fleets",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("region", sa.String(length=120), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_fleets_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fleets")),
        sa.UniqueConstraint("organization_id", "name", name="uq_fleets_org_name"),
    )
    op.create_index("ix_fleets_organization_id", "fleets", ["organization_id"], unique=False)
    op.create_table(
        "vehicle_groups",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_vehicle_groups_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle_groups")),
        sa.UniqueConstraint("organization_id", "name", name="uq_vehicle_groups_org_name"),
    )
    op.create_index(
        "ix_vehicle_groups_organization_id", "vehicle_groups", ["organization_id"], unique=False
    )
    op.create_table(
        "vehicles",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("fleet_id", sa.UUID(), nullable=True),
        sa.Column("vehicle_group_id", sa.UUID(), nullable=True),
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column("plate", sa.String(length=20), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("make", sa.String(length=80), nullable=True),
        sa.Column("model", sa.String(length=80), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','inactive','maintenance')", name=op.f("ck_vehicles_status_valid")
        ),
        sa.CheckConstraint(
            "year IS NULL OR (year BETWEEN 1950 AND 2100)", name=op.f("ck_vehicles_year_range")
        ),
        sa.ForeignKeyConstraint(
            ["fleet_id"],
            ["fleets.id"],
            name=op.f("fk_vehicles_fleet_id_fleets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_vehicles_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_group_id"],
            ["vehicle_groups.id"],
            name=op.f("fk_vehicles_vehicle_group_id_vehicle_groups"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
        sa.UniqueConstraint("organization_id", "external_id", name="uq_vehicles_org_external"),
    )
    op.create_index("ix_vehicles_fleet_id", "vehicles", ["fleet_id"], unique=False)
    op.create_index("ix_vehicles_organization_id", "vehicles", ["organization_id"], unique=False)
    op.create_table(
        "devices",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=True),
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('telematics','dashcam','sensor','gateway')",
            name=op.f("ck_devices_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active','inactive','offline')", name=op.f("ck_devices_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_devices_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_devices_vehicle_id_vehicles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("organization_id", "external_id", name="uq_devices_org_external"),
    )
    op.create_index("ix_devices_organization_id", "devices", ["organization_id"], unique=False)
    op.create_index("ix_devices_vehicle_id", "devices", ["vehicle_id"], unique=False)
    op.create_table(
        "driver_assignments",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("driver_id", sa.UUID(), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
            name=op.f("fk_driver_assignments_driver_id_drivers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_driver_assignments_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_driver_assignments_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_driver_assignments")),
    )
    op.create_index(
        "ix_driver_assignments_driver_id", "driver_assignments", ["driver_id"], unique=False
    )
    op.create_index(
        "ix_driver_assignments_organization_id",
        "driver_assignments",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_driver_assignments_vehicle_id", "driver_assignments", ["vehicle_id"], unique=False
    )
    op.create_index(
        "uq_driver_assignments_open_vehicle",
        "driver_assignments",
        ["vehicle_id"],
        unique=True,
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.create_table(
        "cameras",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("vehicle_id", sa.UUID(), nullable=True),
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column("position", sa.String(length=20), nullable=False),
        sa.Column("connection_ref", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "position IN ('road','driver','cabin','rear')", name=op.f("ck_cameras_position_valid")
        ),
        sa.CheckConstraint(
            "status IN ('active','inactive','obstructed','offline')",
            name=op.f("ck_cameras_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_cameras_device_id_devices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_cameras_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_cameras_vehicle_id_vehicles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cameras")),
        sa.UniqueConstraint("organization_id", "external_id", name="uq_cameras_org_external"),
    )
    op.create_index("ix_cameras_organization_id", "cameras", ["organization_id"], unique=False)

    # --- Row-Level Security: tenant isolation for all fleet tables (ADR-0010) ---
    op.execute("ALTER TABLE fleets ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE fleets FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY fleets_tenant_isolation ON fleets "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    op.execute("ALTER TABLE vehicle_groups ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE vehicle_groups FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY vehicle_groups_tenant_isolation ON vehicle_groups "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    op.execute("ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE vehicles FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY vehicles_tenant_isolation ON vehicles "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    op.execute("ALTER TABLE drivers ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE drivers FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY drivers_tenant_isolation ON drivers "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    op.execute("ALTER TABLE driver_assignments ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE driver_assignments FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY driver_assignments_tenant_isolation ON driver_assignments "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    op.execute("ALTER TABLE devices ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE devices FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY devices_tenant_isolation ON devices "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    op.execute("ALTER TABLE cameras ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE cameras FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY cameras_tenant_isolation ON cameras "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cameras_organization_id", table_name="cameras")
    op.drop_table("cameras")
    op.drop_index(
        "uq_driver_assignments_open_vehicle",
        table_name="driver_assignments",
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.drop_index("ix_driver_assignments_vehicle_id", table_name="driver_assignments")
    op.drop_index("ix_driver_assignments_organization_id", table_name="driver_assignments")
    op.drop_index("ix_driver_assignments_driver_id", table_name="driver_assignments")
    op.drop_table("driver_assignments")
    op.drop_index("ix_devices_vehicle_id", table_name="devices")
    op.drop_index("ix_devices_organization_id", table_name="devices")
    op.drop_table("devices")
    op.drop_index("ix_vehicles_organization_id", table_name="vehicles")
    op.drop_index("ix_vehicles_fleet_id", table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index("ix_vehicle_groups_organization_id", table_name="vehicle_groups")
    op.drop_table("vehicle_groups")
    op.drop_index("ix_fleets_organization_id", table_name="fleets")
    op.drop_table("fleets")
    op.drop_index("ix_drivers_organization_id", table_name="drivers")
    op.drop_table("drivers")
    # ### end Alembic commands ###
