"""ingestion tables

Revision ID: 4681a4f1b1a3
Revises: 40b5ec956b93
Create Date: 2026-07-17 07:40:18.087570+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4681a4f1b1a3"
down_revision: str | None = "40b5ec956b93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("source_key", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("license", sa.String(length=200), nullable=True),
        sa.Column("attribution", sa.String(length=300), nullable=True),
        sa.Column("refresh_interval_seconds", sa.Integer(), nullable=True),
        sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rejected_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duplicate_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('rest','webhook','mqtt','kafka','s3_batch','csv','simulator')",
            name=op.f("ck_data_sources_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active','paused','disabled')", name=op.f("ck_data_sources_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_data_sources_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
        sa.UniqueConstraint("organization_id", "source_key", name="uq_data_sources_org_key"),
    )
    op.create_index(
        "ix_data_sources_organization_id", "data_sources", ["organization_id"], unique=False
    )
    op.create_table(
        "ingest_events",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("data_source_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("external_event_id", sa.String(length=200), nullable=False),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("vehicle_external_id", sa.String(length=120), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("envelope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="accepted", nullable=False),
        sa.Column("rejection_reason", sa.String(length=60), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('accepted','processing','processed','quarantined','dead_letter')",
            name=op.f("ck_ingest_events_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_ingest_events_data_source_id_data_sources"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ingest_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_events")),
        sa.UniqueConstraint(
            "organization_id", "source", "external_event_id", name="uq_ingest_events_dedup"
        ),
    )
    op.create_index(
        "ix_ingest_events_org_received",
        "ingest_events",
        ["organization_id", "received_at"],
        unique=False,
    )
    op.create_index(
        "ix_ingest_events_status", "ingest_events", ["status", "received_at"], unique=False
    )
    op.create_index(
        "ix_ingest_events_vehicle",
        "ingest_events",
        ["organization_id", "vehicle_external_id"],
        unique=False,
    )
    op.create_table(
        "data_source_credentials_metadata",
        sa.Column("data_source_id", sa.UUID(), nullable=False),
        sa.Column("secret_ref", sa.String(length=300), nullable=True),
        sa.Column("api_token_id", sa.UUID(), nullable=True),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotation_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_token_id"],
            ["api_tokens.id"],
            name=op.f("fk_data_source_credentials_metadata_api_token_id_api_tokens"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_data_source_credentials_metadata_data_source_id_data_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("data_source_id", name=op.f("pk_data_source_credentials_metadata")),
    )

    # --- Row-Level Security for tenant-bound ingestion tables (ADR-0010) ---
    op.execute("ALTER TABLE data_sources ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE data_sources FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY data_sources_tenant_isolation ON data_sources "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    op.execute("ALTER TABLE ingest_events ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE ingest_events FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY ingest_events_tenant_isolation ON ingest_events "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_source_credentials_metadata")
    op.drop_index("ix_ingest_events_vehicle", table_name="ingest_events")
    op.drop_index("ix_ingest_events_status", table_name="ingest_events")
    op.drop_index("ix_ingest_events_org_received", table_name="ingest_events")
    op.drop_table("ingest_events")
    op.drop_index("ix_data_sources_organization_id", table_name="data_sources")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
