"""notifications and webhooks

Revision ID: 5bb4725f991b
Revises: 6c3942493d54
Create Date: 2026-07-19 13:45:24.996801+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5bb4725f991b"
down_revision: str | None = "6c3942493d54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_rules",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("min_severity", sa.String(length=20), server_default="high", nullable=False),
        sa.Column(
            "channels",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='["in_app"]',
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('severity_threshold','device_offline','geofence')",
            name=op.f("ck_notification_rules_kind_valid"),
        ),
        sa.CheckConstraint(
            "min_severity IN ('low','medium','high','critical')",
            name=op.f("ck_notification_rules_min_severity_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_notification_rules_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_rules")),
    )
    op.create_index(
        "ix_notification_rules_org", "notification_rules", ["organization_id"], unique=False
    )
    op.create_table(
        "webhook_endpoints",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column("secret", sa.String(length=100), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_webhook_endpoints_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_endpoints")),
    )
    op.create_index(
        "ix_webhook_endpoints_org", "webhook_endpoints", ["organization_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("safety_event_id", sa.UUID(), nullable=True),
        sa.Column("level", sa.String(length=20), server_default="info", nullable=False),
        sa.Column("title_tr", sa.String(length=300), nullable=False),
        sa.Column("body_tr", sa.Text(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "level IN ('info','warning','critical')", name=op.f("ck_notifications_level_valid")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_notifications_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["notification_rules.id"],
            name=op.f("fk_notifications_rule_id_notification_rules"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_org_created",
        "notifications",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "webhook_deliveries",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("endpoint_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','delivered','failed','dead_letter')",
            name=op.f("ck_webhook_deliveries_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["webhook_endpoints.id"],
            name=op.f("fk_webhook_deliveries_endpoint_id_webhook_endpoints"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_deliveries")),
    )
    op.create_index(
        "ix_webhook_deliveries_org", "webhook_deliveries", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_webhook_deliveries_pending",
        "webhook_deliveries",
        ["status", "next_attempt_at"],
        unique=False,
    )

    # --- Row-Level Security (ADR-0010) ---
    op.execute("ALTER TABLE notification_rules ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE notification_rules FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY notification_rules_tenant_isolation ON notification_rules "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    op.execute("ALTER TABLE notifications ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE notifications FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY notifications_tenant_isolation ON notifications "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    op.execute("ALTER TABLE webhook_endpoints ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE webhook_endpoints FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY webhook_endpoints_tenant_isolation ON webhook_endpoints "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    op.execute("ALTER TABLE webhook_deliveries ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE webhook_deliveries FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY webhook_deliveries_tenant_isolation ON webhook_deliveries "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_webhook_deliveries_pending", table_name="webhook_deliveries")
    op.drop_index("ix_webhook_deliveries_org", table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    op.drop_index("ix_notifications_org_created", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_webhook_endpoints_org", table_name="webhook_endpoints")
    op.drop_table("webhook_endpoints")
    op.drop_index("ix_notification_rules_org", table_name="notification_rules")
    op.drop_table("notification_rules")
    # ### end Alembic commands ###
