"""safety events

Revision ID: 681d84144356
Revises: 8eaded5cfb16
Create Date: 2026-07-17 08:03:00.436707+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "681d84144356"
down_revision: str | None = "8eaded5cfb16"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "safety_events",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("driver_id", sa.UUID(), nullable=True),
        sa.Column("trip_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("measured_value", sa.Float(), nullable=True),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.Column("reason_tr", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=40), server_default="rule_engine", nullable=False),
        sa.Column("ruleset_version", sa.Integer(), nullable=False),
        sa.Column("severity_framework_version", sa.Integer(), nullable=False),
        sa.Column("data_quality", sa.Float(), nullable=True),
        sa.Column("processing_status", sa.String(length=20), server_default="new", nullable=False),
        sa.Column("review_status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("reviewer_user_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.String(length=40), nullable=True),
        sa.Column("root_cause", sa.String(length=60), nullable=True),
        sa.Column("reviewer_notes", sa.Text(), nullable=True),
        sa.Column("needs_review", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("dedup_key", sa.String(length=200), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "processing_status IN ('new','processed','error')",
            name=op.f("ck_safety_events_processing_status_valid"),
        ),
        sa.CheckConstraint(
            "review_status IN ('pending','confirmed','rejected','uncertain')",
            name=op.f("ck_safety_events_review_status_valid"),
        ),
        sa.CheckConstraint(
            "severity IN ('low','medium','high','critical')",
            name=op.f("ck_safety_events_severity_valid"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_safety_events_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_safety_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_safety_events")),
        sa.UniqueConstraint("organization_id", "dedup_key", name="uq_safety_events_dedup"),
    )
    op.create_index(
        "ix_safety_events_driver",
        "safety_events",
        ["organization_id", "driver_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_safety_events_org_occurred",
        "safety_events",
        ["organization_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_safety_events_org_review",
        "safety_events",
        ["organization_id", "review_status"],
        unique=False,
    )
    op.create_index(
        "ix_safety_events_vehicle",
        "safety_events",
        ["organization_id", "vehicle_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "event_evidence",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("safety_event_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("telemetry_window", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("storage_key", sa.String(length=400), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('telemetry_window','snapshot','clip','note')",
            name=op.f("ck_event_evidence_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["safety_event_id"],
            ["safety_events.id"],
            name=op.f("fk_event_evidence_safety_event_id_safety_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_evidence")),
    )
    op.create_index(
        "ix_event_evidence_safety_event_id", "event_evidence", ["safety_event_id"], unique=False
    )

    # --- Row-Level Security for safety tables (ADR-0010) ---
    op.execute("ALTER TABLE safety_events ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE safety_events FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY safety_events_tenant_isolation ON safety_events "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    op.execute("ALTER TABLE event_evidence ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE event_evidence FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY event_evidence_tenant_isolation ON event_evidence "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_event_evidence_safety_event_id", table_name="event_evidence")
    op.drop_table("event_evidence")
    op.drop_index("ix_safety_events_vehicle", table_name="safety_events")
    op.drop_index("ix_safety_events_org_review", table_name="safety_events")
    op.drop_index("ix_safety_events_org_occurred", table_name="safety_events")
    op.drop_index("ix_safety_events_driver", table_name="safety_events")
    op.drop_table("safety_events")
    # ### end Alembic commands ###
