"""road risks and geofences

Revision ID: 6c3942493d54
Revises: 681d84144356
Create Date: 2026-07-17 08:11:48.919250+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6c3942493d54"
down_revision: str | None = "681d84144356"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geofences",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=30), server_default="high_risk", nullable=False),
        sa.Column("center_latitude", sa.Float(), nullable=False),
        sa.Column("center_longitude", sa.Float(), nullable=False),
        sa.Column("radius_m", sa.Float(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('high_risk','depot','restricted','custom')",
            name=op.f("ck_geofences_kind_valid"),
        ),
        sa.CheckConstraint(
            "radius_m > 0 AND radius_m <= 100000", name=op.f("ck_geofences_radius_range")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_geofences_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_geofences")),
    )
    op.create_index("ix_geofences_org", "geofences", ["organization_id"], unique=False)
    op.create_table(
        "road_risks",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("risk_type", sa.String(length=50), nullable=False),
        sa.Column("center_latitude", sa.Float(), nullable=False),
        sa.Column("center_longitude", sa.Float(), nullable=False),
        sa.Column("radius_m", sa.Float(), server_default="150", nullable=False),
        sa.Column("observed_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("inferred_severity", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=40), server_default="event_cluster", nullable=False),
        sa.Column("source_reliability", sa.Float(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "inferred_severity IN ('low','medium','high','critical')",
            name=op.f("ck_road_risks_inferred_severity_valid"),
        ),
        sa.CheckConstraint(
            "review_status IN ('pending','confirmed','rejected')",
            name=op.f("ck_road_risks_review_status_valid"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_road_risks_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_road_risks_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_road_risks")),
    )
    op.create_index("ix_road_risks_org", "road_risks", ["organization_id"], unique=False)
    op.create_index(
        "ix_road_risks_org_type", "road_risks", ["organization_id", "risk_type"], unique=False
    )

    # --- Row-Level Security (ADR-0010) ---
    op.execute("ALTER TABLE road_risks ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE road_risks FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY road_risks_tenant_isolation ON road_risks "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    op.execute("ALTER TABLE geofences ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE geofences FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY geofences_tenant_isolation ON geofences "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_road_risks_org_type", table_name="road_risks")
    op.drop_index("ix_road_risks_org", table_name="road_risks")
    op.drop_table("road_risks")
    op.drop_index("ix_geofences_org", table_name="geofences")
    op.drop_table("geofences")
    # ### end Alembic commands ###
