"""saas plans and subscriptions

Revision ID: 6e3bcf315d54
Revises: 5bb4725f991b
Create Date: 2026-07-19 13:50:41.386261+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6e3bcf315d54"
down_revision: str | None = "5bb4725f991b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plans",
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("name_tr", sa.String(length=100), nullable=False),
        sa.Column("vehicle_limit", sa.Integer(), nullable=False),
        sa.Column("user_limit", sa.Integer(), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column(
            "features", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("monthly_price_try", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_plans")),
    )
    op.create_table(
        "usage_records",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("metric", sa.String(length=60), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_records")),
    )
    op.create_index(
        "ix_usage_records_org_metric",
        "usage_records",
        ["organization_id", "metric", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "subscriptions",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("plan_key", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="trial", nullable=False),
        sa.Column(
            "billing_mode", sa.String(length=20), server_default="manual_invoice", nullable=False
        ),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "billing_mode IN ('manual_invoice','stripe')",
            name=op.f("ck_subscriptions_billing_mode_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('trial','active','past_due','canceled')",
            name=op.f("ck_subscriptions_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_subscriptions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_key"], ["plans.key"], name=op.f("fk_subscriptions_plan_key_plans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint("organization_id", name=op.f("uq_subscriptions_organization_id")),
    )

    # --- Plan catalog seed (mirrors visionroute.application.saas.service) ---
    plans_table = sa.table(
        "plans",
        sa.column("key", sa.String),
        sa.column("name_tr", sa.String),
        sa.column("vehicle_limit", sa.Integer),
        sa.column("user_limit", sa.Integer),
        sa.column("retention_days", sa.Integer),
        sa.column("monthly_price_try", sa.Float),
    )
    op.bulk_insert(
        plans_table,
        [
            {
                "key": "baslangic",
                "name_tr": "Başlangıç",
                "vehicle_limit": 10,
                "user_limit": 5,
                "retention_days": 90,
                "monthly_price_try": 4900.0,
            },
            {
                "key": "profesyonel",
                "name_tr": "Profesyonel",
                "vehicle_limit": 100,
                "user_limit": 25,
                "retention_days": 365,
                "monthly_price_try": 19900.0,
            },
            {
                "key": "kurumsal",
                "name_tr": "Kurumsal",
                "vehicle_limit": -1,
                "user_limit": -1,
                "retention_days": 730,
                "monthly_price_try": None,
            },
        ],
    )

    # --- RLS for tenant-bound SaaS tables (plans is a global catalog) ---
    op.execute("ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE subscriptions FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY subscriptions_tenant_isolation ON subscriptions "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    op.execute("ALTER TABLE usage_records ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE usage_records FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY usage_records_tenant_isolation ON usage_records "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscriptions")
    op.drop_index("ix_usage_records_org_metric", table_name="usage_records")
    op.drop_table("usage_records")
    op.drop_table("plans")
    # ### end Alembic commands ###
