"""coaching actions

Coaching workflow table (RLS), one active action per safety event.

Revision ID: 8c3d5e7f9a21
Revises: 7b2c4d6e8f10
Create Date: 2026-09-14 08:05:22.837957+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "8c3d5e7f9a21"
down_revision: str | None = "7b2c4d6e8f10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coaching_actions",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("safety_event_id", sa.UUID(), nullable=True),
        sa.Column("driver_id", sa.UUID(), nullable=True),
        sa.Column("assignee_user_id", sa.UUID(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="open", nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("outcome", sa.String(length=30), nullable=True),
        sa.Column("outcome_notes", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.String(length=300), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IS NULL OR outcome IN "
            "('coached','no_action_needed','escalated','driver_unavailable')",
            name=op.f("ck_coaching_actions_outcome_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('open','in_progress','completed','canceled')",
            name=op.f("ck_coaching_actions_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["assignee_user_id"],
            ["users.id"],
            name=op.f("fk_coaching_actions_assignee_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_coaching_actions_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
            name=op.f("fk_coaching_actions_driver_id_drivers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_coaching_actions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["safety_event_id"],
            ["safety_events.id"],
            name=op.f("fk_coaching_actions_safety_event_id_safety_events"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coaching_actions")),
    )
    op.create_index(
        "ix_coaching_actions_org_assignee",
        "coaching_actions",
        ["organization_id", "assignee_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_coaching_actions_org_driver",
        "coaching_actions",
        ["organization_id", "driver_id"],
        unique=False,
    )
    op.create_index(
        "ix_coaching_actions_org_status",
        "coaching_actions",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_coaching_actions_active_event",
        "coaching_actions",
        ["organization_id", "safety_event_id"],
        unique=True,
        postgresql_where=sa.text(
            "safety_event_id IS NOT NULL AND status IN ('open','in_progress')"
        ),
    )
    op.execute("ALTER TABLE coaching_actions ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE coaching_actions FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY coaching_actions_tenant_isolation ON coaching_actions "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_coaching_actions_active_event",
        table_name="coaching_actions",
        postgresql_where=sa.text(
            "safety_event_id IS NOT NULL AND status IN ('open','in_progress')"
        ),
    )
    op.drop_index("ix_coaching_actions_org_status", table_name="coaching_actions")
    op.drop_index("ix_coaching_actions_org_driver", table_name="coaching_actions")
    op.drop_index("ix_coaching_actions_org_assignee", table_name="coaching_actions")
    op.drop_table("coaching_actions")
    # ### end Alembic commands ###
