"""trips and telemetry

Revision ID: 8eaded5cfb16
Revises: 4681a4f1b1a3
Create Date: 2026-07-17 07:49:53.547634+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8eaded5cfb16"
down_revision: str | None = "4681a4f1b1a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telemetry_aggregates",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("bucket_hour", sa.DateTime(timezone=True), nullable=False),
        sa.Column("point_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("distance_km", sa.Float(), server_default="0", nullable=False),
        sa.Column("max_speed_kph", sa.Float(), nullable=True),
        sa.Column("avg_speed_kph", sa.Float(), nullable=True),
        sa.Column("data_quality_avg", sa.Float(), nullable=True),
        sa.Column(
            "metrics", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telemetry_aggregates")),
    )
    op.create_index(
        "uq_telemetry_aggregates_bucket",
        "telemetry_aggregates",
        ["organization_id", "vehicle_id", "bucket_hour"],
        unique=True,
    )
    op.create_table(
        "trips",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("driver_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_point_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("distance_km", sa.Float(), server_default="0", nullable=False),
        sa.Column("point_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_speed_kph", sa.Float(), nullable=True),
        sa.Column("last_latitude", sa.Float(), nullable=True),
        sa.Column("last_longitude", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','completed','stale')", name=op.f("ck_trips_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
            name=op.f("fk_trips_driver_id_drivers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_trips_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_trips_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trips")),
    )
    op.create_index("ix_trips_org_status", "trips", ["organization_id", "status"], unique=False)
    op.create_index("ix_trips_organization_id", "trips", ["organization_id"], unique=False)
    op.create_index("ix_trips_vehicle_status", "trips", ["vehicle_id", "status"], unique=False)
    op.create_table(
        "trip_segments",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("trip_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("distance_km", sa.Float(), server_default="0", nullable=False),
        sa.Column("avg_speed_kph", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_trip_segments_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trip_segments")),
    )
    op.create_index("ix_trip_segments_trip_id", "trip_segments", ["trip_id"], unique=False)

    # --- telemetry_points: range-partitioned by occurred_at (monthly) ---
    op.execute(
        """
        CREATE TABLE telemetry_points (
            id uuid NOT NULL,
            occurred_at timestamptz NOT NULL,
            organization_id uuid NOT NULL,
            trip_id uuid,
            vehicle_id uuid NOT NULL,
            driver_id uuid,
            latitude double precision NOT NULL,
            longitude double precision NOT NULL,
            speed_kph double precision,
            heading_deg double precision,
            acceleration_ms2 double precision,
            lateral_acceleration_ms2 double precision,
            quality double precision NOT NULL DEFAULT 1.0,
            PRIMARY KEY (id, occurred_at)
        ) PARTITION BY RANGE (occurred_at)
        """
    )
    op.execute(
        "CREATE INDEX ix_telemetry_points_org_vehicle_time "
        "ON telemetry_points (organization_id, vehicle_id, occurred_at)"
    )
    op.execute("CREATE INDEX ix_telemetry_points_trip ON telemetry_points (trip_id, occurred_at)")
    # A DEFAULT partition catches any out-of-range rows so inserts never fail;
    # monthly partitions are pre-created for the current window and are
    # extended by the scheduler (ensure_telemetry_partitions job).
    op.execute("CREATE TABLE telemetry_points_default PARTITION OF telemetry_points DEFAULT")
    op.execute(
        """
        DO $$
        DECLARE
            start_month date := date_trunc('month', now())::date - interval '1 month';
            i int;
            p_start date;
            p_end date;
            p_name text;
        BEGIN
            FOR i IN 0..3 LOOP
                p_start := (start_month + (i || ' month')::interval)::date;
                p_end := (start_month + ((i + 1) || ' month')::interval)::date;
                p_name := 'telemetry_points_' || to_char(p_start, 'YYYYMM');
                EXECUTE format(
                    'CREATE TABLE IF NOT EXISTS %I PARTITION OF telemetry_points '
                    'FOR VALUES FROM (%L) TO (%L)', p_name, p_start, p_end
                );
            END LOOP;
        END $$
        """
    )
    op.execute("ALTER TABLE telemetry_points ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE telemetry_points FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY telemetry_points_tenant_isolation ON telemetry_points "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )

    op.execute("ALTER TABLE trips ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE trips FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY trips_tenant_isolation ON trips "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    op.execute("ALTER TABLE trip_segments ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE trip_segments FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY trip_segments_tenant_isolation ON trip_segments "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    op.execute("ALTER TABLE telemetry_aggregates ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE telemetry_aggregates FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY telemetry_aggregates_tenant_isolation ON telemetry_aggregates "
        "USING (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (current_setting('app.rls_bypass', true) = 'on' "
        "OR organization_id::text = current_setting('app.tenant_id', true))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS telemetry_points CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trip_segments_trip_id", table_name="trip_segments")
    op.drop_table("trip_segments")
    op.drop_index("ix_trips_vehicle_status", table_name="trips")
    op.drop_index("ix_trips_organization_id", table_name="trips")
    op.drop_index("ix_trips_org_status", table_name="trips")
    op.drop_table("trips")
    op.drop_index("uq_telemetry_aggregates_bucket", table_name="telemetry_aggregates")
    op.drop_table("telemetry_aggregates")
    # ### end Alembic commands ###
