"""identity and system tables

Revision ID: dc41d0b4983b
Revises:
Create Date: 2026-07-16 11:28:56.810700+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "dc41d0b4983b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_label", sa.String(length=320), server_default="system", nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("resource_type", sa.String(length=60), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_logs_action", "audit_logs", ["action"], unique=False)
    op.create_index(
        "ix_audit_logs_org_created", "audit_logs", ["organization_id", "created_at"], unique=False
    )
    op.create_table(
        "background_jobs",
        sa.Column("job_type", sa.String(length=80), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="5", nullable=False),
        sa.Column(
            "run_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','running','done','failed','dead_letter')",
            name=op.f("ck_background_jobs_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_background_jobs")),
    )
    op.create_index(
        "ix_background_jobs_pending", "background_jobs", ["status", "run_at"], unique=False
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("endpoint", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", "organization_id", name=op.f("pk_idempotency_keys")),
    )
    op.create_index(
        "ix_idempotency_keys_expires_at", "idempotency_keys", ["expires_at"], unique=False
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9][a-z0-9-]{1,78}[a-z0-9]$'", name=op.f("ck_organizations_slug_format")
        ),
        sa.CheckConstraint(
            "status IN ('active','suspended','closed')", name=op.f("ck_organizations_status_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "outbox_events",
        sa.Column("aggregate_type", sa.String(length=60), nullable=False),
        sa.Column("aggregate_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','processing','done','dead_letter')",
            name=op.f("ck_outbox_events_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        "ix_outbox_events_pending", "outbox_events", ["status", "next_attempt_at"], unique=False
    )
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("description_tr", sa.String(length=200), server_default="", nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_permissions")),
    )
    op.create_table(
        "roles",
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("label_tr", sa.String(length=100), nullable=False),
        sa.Column("is_system", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("catalog_version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_roles")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("locale", sa.String(length=10), server_default="tr", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("platform_role", sa.String(length=30), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mfa_totp_secret_enc", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "platform_role IS NULL OR platform_role IN ('super_admin','support')",
            name=op.f("ck_users_platform_role_valid"),
        ),
        sa.CheckConstraint("status IN ('active','disabled')", name=op.f("ck_users_status_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "ix_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "api_clients",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','disabled')", name=op.f("ck_api_clients_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_api_clients_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_api_clients_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_clients")),
    )
    op.create_index(
        "ix_api_clients_organization_id", "api_clients", ["organization_id"], unique=False
    )
    op.create_table(
        "invitations",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role_key", sa.String(length=40), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("invited_by_user_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
            name=op.f("fk_invitations_invited_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_invitations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_key"], ["roles.key"], name=op.f("fk_invitations_role_key_roles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invitations_token_hash")),
    )
    op.create_index(
        "ix_invitations_organization_id", "invitations", ["organization_id"], unique=False
    )
    op.create_table(
        "memberships",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("role_key", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','suspended')", name=op.f("ck_memberships_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_key"], ["roles.key"], name=op.f("fk_memberships_role_key_roles")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint("user_id", "organization_id", name="uq_memberships_user_org"),
    )
    op.create_index(
        "ix_memberships_organization_id", "memberships", ["organization_id"], unique=False
    )
    op.create_table(
        "organization_settings",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "timezone", sa.String(length=60), server_default="Europe/Istanbul", nullable=False
        ),
        sa.Column("currency", sa.String(length=3), server_default="TRY", nullable=False),
        sa.Column(
            "risk_thresholds",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "retention",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_settings_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("organization_id", name=op.f("pk_organization_settings")),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_key", sa.String(length=40), nullable=False),
        sa.Column("permission_code", sa.String(length=60), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_code"],
            ["permissions.code"],
            name=op.f("fk_role_permissions_permission_code_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_key"],
            ["roles.key"],
            name=op.f("fk_role_permissions_role_key_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_key", "permission_code", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reuse_detected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sessions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("refresh_token_hash", name=op.f("uq_sessions_refresh_token_hash")),
    )
    op.create_index("ix_sessions_family_id", "sessions", ["family_id"], unique=False)
    op.create_index("ix_sessions_user_id", "sessions", ["user_id"], unique=False)
    op.create_table(
        "api_tokens",
        sa.Column("api_client_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.String(length=60)), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_client_id"],
            ["api_clients.id"],
            name=op.f("fk_api_tokens_api_client_id_api_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_api_tokens_token_hash")),
    )
    op.create_index("ix_api_tokens_api_client_id", "api_tokens", ["api_client_id"], unique=False)

    # --- RBAC seed: frozen snapshot of visionroute.domain.permissions v1 ---
    roles_table = sa.table(
        "roles",
        sa.column("key", sa.String),
        sa.column("label_tr", sa.String),
        sa.column("is_system", sa.Boolean),
        sa.column("catalog_version", sa.Integer),
    )
    op.bulk_insert(
        roles_table,
        [
            {
                "key": "owner",
                "label_tr": "Organizasyon Sahibi",
                "is_system": True,
                "catalog_version": 1,
            },
            {
                "key": "admin",
                "label_tr": "Organizasyon Yöneticisi",
                "is_system": True,
                "catalog_version": 1,
            },
            {
                "key": "safety_manager",
                "label_tr": "Güvenlik Müdürü",
                "is_system": True,
                "catalog_version": 1,
            },
            {
                "key": "fleet_manager",
                "label_tr": "Filo Yöneticisi",
                "is_system": True,
                "catalog_version": 1,
            },
            {
                "key": "event_reviewer",
                "label_tr": "Olay İnceleyici",
                "is_system": True,
                "catalog_version": 1,
            },
            {"key": "coach", "label_tr": "Sürücü Koçu", "is_system": True, "catalog_version": 1},
            {"key": "analyst", "label_tr": "Analist", "is_system": True, "catalog_version": 1},
            {
                "key": "auditor",
                "label_tr": "Salt Okunur Denetçi",
                "is_system": True,
                "catalog_version": 1,
            },
            {
                "key": "integration_manager",
                "label_tr": "Entegrasyon Yöneticisi",
                "is_system": True,
                "catalog_version": 1,
            },
            {
                "key": "driver",
                "label_tr": "Sürücü (Self Servis)",
                "is_system": True,
                "catalog_version": 1,
            },
        ],
    )
    permissions_table = sa.table("permissions", sa.column("code", sa.String))
    op.bulk_insert(
        permissions_table,
        [
            {"code": "analytics.read"},
            {"code": "audit.read"},
            {"code": "coaching.manage"},
            {"code": "coaching.read"},
            {"code": "events.evidence.raw_media"},
            {"code": "events.evidence.read"},
            {"code": "events.read"},
            {"code": "events.review"},
            {"code": "fleet.manage"},
            {"code": "fleet.read"},
            {"code": "geofences.manage"},
            {"code": "integrations.manage"},
            {"code": "integrations.read"},
            {"code": "notifications.manage"},
            {"code": "org.invitations.manage"},
            {"code": "org.members.manage"},
            {"code": "org.members.read"},
            {"code": "org.read"},
            {"code": "org.retention.manage"},
            {"code": "org.update"},
            {"code": "reports.manage"},
            {"code": "reports.read"},
            {"code": "risks.manage"},
            {"code": "risks.read"},
            {"code": "subscription.manage"},
            {"code": "subscription.read"},
            {"code": "telemetry.read"},
            {"code": "trips.read"},
        ],
    )
    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_key", sa.String),
        sa.column("permission_code", sa.String),
    )
    op.bulk_insert(
        role_permissions_table,
        [
            {"role_key": "admin", "permission_code": "analytics.read"},
            {"role_key": "admin", "permission_code": "audit.read"},
            {"role_key": "admin", "permission_code": "coaching.manage"},
            {"role_key": "admin", "permission_code": "coaching.read"},
            {"role_key": "admin", "permission_code": "events.evidence.raw_media"},
            {"role_key": "admin", "permission_code": "events.evidence.read"},
            {"role_key": "admin", "permission_code": "events.read"},
            {"role_key": "admin", "permission_code": "events.review"},
            {"role_key": "admin", "permission_code": "fleet.manage"},
            {"role_key": "admin", "permission_code": "fleet.read"},
            {"role_key": "admin", "permission_code": "geofences.manage"},
            {"role_key": "admin", "permission_code": "integrations.manage"},
            {"role_key": "admin", "permission_code": "integrations.read"},
            {"role_key": "admin", "permission_code": "notifications.manage"},
            {"role_key": "admin", "permission_code": "org.invitations.manage"},
            {"role_key": "admin", "permission_code": "org.members.manage"},
            {"role_key": "admin", "permission_code": "org.members.read"},
            {"role_key": "admin", "permission_code": "org.read"},
            {"role_key": "admin", "permission_code": "org.retention.manage"},
            {"role_key": "admin", "permission_code": "org.update"},
            {"role_key": "admin", "permission_code": "reports.manage"},
            {"role_key": "admin", "permission_code": "reports.read"},
            {"role_key": "admin", "permission_code": "risks.manage"},
            {"role_key": "admin", "permission_code": "risks.read"},
            {"role_key": "admin", "permission_code": "subscription.read"},
            {"role_key": "admin", "permission_code": "telemetry.read"},
            {"role_key": "admin", "permission_code": "trips.read"},
            {"role_key": "analyst", "permission_code": "analytics.read"},
            {"role_key": "analyst", "permission_code": "events.read"},
            {"role_key": "analyst", "permission_code": "fleet.read"},
            {"role_key": "analyst", "permission_code": "org.read"},
            {"role_key": "analyst", "permission_code": "reports.manage"},
            {"role_key": "analyst", "permission_code": "reports.read"},
            {"role_key": "analyst", "permission_code": "risks.read"},
            {"role_key": "analyst", "permission_code": "trips.read"},
            {"role_key": "auditor", "permission_code": "analytics.read"},
            {"role_key": "auditor", "permission_code": "audit.read"},
            {"role_key": "auditor", "permission_code": "coaching.read"},
            {"role_key": "auditor", "permission_code": "events.read"},
            {"role_key": "auditor", "permission_code": "fleet.read"},
            {"role_key": "auditor", "permission_code": "org.members.read"},
            {"role_key": "auditor", "permission_code": "org.read"},
            {"role_key": "auditor", "permission_code": "reports.read"},
            {"role_key": "auditor", "permission_code": "risks.read"},
            {"role_key": "auditor", "permission_code": "subscription.read"},
            {"role_key": "auditor", "permission_code": "trips.read"},
            {"role_key": "coach", "permission_code": "analytics.read"},
            {"role_key": "coach", "permission_code": "coaching.manage"},
            {"role_key": "coach", "permission_code": "coaching.read"},
            {"role_key": "coach", "permission_code": "events.evidence.read"},
            {"role_key": "coach", "permission_code": "events.read"},
            {"role_key": "coach", "permission_code": "fleet.read"},
            {"role_key": "coach", "permission_code": "org.read"},
            {"role_key": "driver", "permission_code": "coaching.read"},
            {"role_key": "event_reviewer", "permission_code": "events.evidence.read"},
            {"role_key": "event_reviewer", "permission_code": "events.read"},
            {"role_key": "event_reviewer", "permission_code": "events.review"},
            {"role_key": "event_reviewer", "permission_code": "fleet.read"},
            {"role_key": "event_reviewer", "permission_code": "org.read"},
            {"role_key": "event_reviewer", "permission_code": "risks.read"},
            {"role_key": "event_reviewer", "permission_code": "trips.read"},
            {"role_key": "fleet_manager", "permission_code": "analytics.read"},
            {"role_key": "fleet_manager", "permission_code": "events.read"},
            {"role_key": "fleet_manager", "permission_code": "fleet.manage"},
            {"role_key": "fleet_manager", "permission_code": "fleet.read"},
            {"role_key": "fleet_manager", "permission_code": "org.members.read"},
            {"role_key": "fleet_manager", "permission_code": "org.read"},
            {"role_key": "fleet_manager", "permission_code": "reports.read"},
            {"role_key": "fleet_manager", "permission_code": "risks.read"},
            {"role_key": "fleet_manager", "permission_code": "telemetry.read"},
            {"role_key": "fleet_manager", "permission_code": "trips.read"},
            {"role_key": "integration_manager", "permission_code": "fleet.read"},
            {"role_key": "integration_manager", "permission_code": "integrations.manage"},
            {"role_key": "integration_manager", "permission_code": "integrations.read"},
            {"role_key": "integration_manager", "permission_code": "notifications.manage"},
            {"role_key": "integration_manager", "permission_code": "org.read"},
            {"role_key": "owner", "permission_code": "analytics.read"},
            {"role_key": "owner", "permission_code": "audit.read"},
            {"role_key": "owner", "permission_code": "coaching.manage"},
            {"role_key": "owner", "permission_code": "coaching.read"},
            {"role_key": "owner", "permission_code": "events.evidence.raw_media"},
            {"role_key": "owner", "permission_code": "events.evidence.read"},
            {"role_key": "owner", "permission_code": "events.read"},
            {"role_key": "owner", "permission_code": "events.review"},
            {"role_key": "owner", "permission_code": "fleet.manage"},
            {"role_key": "owner", "permission_code": "fleet.read"},
            {"role_key": "owner", "permission_code": "geofences.manage"},
            {"role_key": "owner", "permission_code": "integrations.manage"},
            {"role_key": "owner", "permission_code": "integrations.read"},
            {"role_key": "owner", "permission_code": "notifications.manage"},
            {"role_key": "owner", "permission_code": "org.invitations.manage"},
            {"role_key": "owner", "permission_code": "org.members.manage"},
            {"role_key": "owner", "permission_code": "org.members.read"},
            {"role_key": "owner", "permission_code": "org.read"},
            {"role_key": "owner", "permission_code": "org.retention.manage"},
            {"role_key": "owner", "permission_code": "org.update"},
            {"role_key": "owner", "permission_code": "reports.manage"},
            {"role_key": "owner", "permission_code": "reports.read"},
            {"role_key": "owner", "permission_code": "risks.manage"},
            {"role_key": "owner", "permission_code": "risks.read"},
            {"role_key": "owner", "permission_code": "subscription.manage"},
            {"role_key": "owner", "permission_code": "subscription.read"},
            {"role_key": "owner", "permission_code": "telemetry.read"},
            {"role_key": "owner", "permission_code": "trips.read"},
            {"role_key": "safety_manager", "permission_code": "analytics.read"},
            {"role_key": "safety_manager", "permission_code": "coaching.manage"},
            {"role_key": "safety_manager", "permission_code": "coaching.read"},
            {"role_key": "safety_manager", "permission_code": "events.evidence.raw_media"},
            {"role_key": "safety_manager", "permission_code": "events.evidence.read"},
            {"role_key": "safety_manager", "permission_code": "events.read"},
            {"role_key": "safety_manager", "permission_code": "events.review"},
            {"role_key": "safety_manager", "permission_code": "fleet.read"},
            {"role_key": "safety_manager", "permission_code": "geofences.manage"},
            {"role_key": "safety_manager", "permission_code": "notifications.manage"},
            {"role_key": "safety_manager", "permission_code": "org.members.read"},
            {"role_key": "safety_manager", "permission_code": "org.read"},
            {"role_key": "safety_manager", "permission_code": "reports.manage"},
            {"role_key": "safety_manager", "permission_code": "reports.read"},
            {"role_key": "safety_manager", "permission_code": "risks.manage"},
            {"role_key": "safety_manager", "permission_code": "risks.read"},
            {"role_key": "safety_manager", "permission_code": "telemetry.read"},
            {"role_key": "safety_manager", "permission_code": "trips.read"},
        ],
    )

    # --- Audit log immutability: append-only enforced in the database too ---
    op.execute(
        """
        CREATE FUNCTION audit_logs_immutable() RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION 'audit_logs tablosu yalnizca eklemeye aciktir (append-only)';
        END $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        "CREATE TRIGGER trg_audit_logs_immutable BEFORE UPDATE OR DELETE ON audit_logs "
        "FOR EACH ROW EXECUTE FUNCTION audit_logs_immutable()"
    )

    # --- Row-Level Security: tenant isolation defense-in-depth (ADR-0010) ---
    # The application sets app.tenant_id per transaction; trusted platform code
    # paths (auth, worker, migrations-adjacent tooling) set app.rls_bypass='on'.
    for table in ("memberships", "invitations", "api_clients", "organization_settings"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_tenant_isolation ON {table}
            USING (
                current_setting('app.rls_bypass', true) = 'on'
                OR organization_id::text = current_setting('app.tenant_id', true)
            )
            WITH CHECK (
                current_setting('app.rls_bypass', true) = 'on'
                OR organization_id::text = current_setting('app.tenant_id', true)
            )
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION IF EXISTS audit_logs_immutable() CASCADE")
    op.drop_index("ix_api_tokens_api_client_id", table_name="api_tokens")
    op.drop_table("api_tokens")
    op.drop_index("ix_sessions_user_id", table_name="sessions")
    op.drop_index("ix_sessions_family_id", table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("role_permissions")
    op.drop_table("organization_settings")
    op.drop_index("ix_memberships_organization_id", table_name="memberships")
    op.drop_table("memberships")
    op.drop_index("ix_invitations_organization_id", table_name="invitations")
    op.drop_table("invitations")
    op.drop_index("ix_api_clients_organization_id", table_name="api_clients")
    op.drop_table("api_clients")
    op.drop_index("ix_users_email_lower", table_name="users")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_index("ix_outbox_events_pending", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_table("organizations")
    op.drop_index("ix_idempotency_keys_expires_at", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index("ix_background_jobs_pending", table_name="background_jobs")
    op.drop_table("background_jobs")
    op.drop_index("ix_audit_logs_org_created", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action", table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
